root = "."               # Project root
tmp_dir = "tmp"           # Temporary build files go here

[build]
    bin = "tmp/main.exe"            # Windows binary
    cmd = "go build -o tmp/main.exe ."  # Build the whole module
    exclude = ["tmp/**", "client/**"]
    include_only = ["**/*.go"]
    ignore = ["tmp/**", "client/**"]
