-- Add AI product analysis fields for Gemini AI feature
-- These columns store data generated from AI analysis of product images

ALTER TABLE products
ADD COLUMN IF NOT EXISTS wants VARCHAR(255) COMMENT 'What the seller is willing to trade/exchange for',
ADD COLUMN IF NOT EXISTS wanted_categories VARCHAR(500) COMMENT 'Categories of items seller wants (JSON array)',
ADD COLUMN IF NOT EXISTS item_type VARCHAR(100) COMMENT 'Type of item detected by AI (e.g., Sneakers, Laptop)',
ADD COLUMN IF NOT EXISTS brand VARCHAR(100) COMMENT 'Brand detected by AI or Unknown',
ADD COLUMN IF NOT EXISTS authenticity_risks VARCHAR(50) COMMENT 'Authenticity risk level: Low, Medium, High',
ADD COLUMN IF NOT EXISTS tags JSON COMMENT 'Searchable tags generated by AI',
ADD COLUMN IF NOT EXISTS estimated_value_min DECIMAL(10,2) COMMENT 'Minimum estimated value (PHP)',
ADD COLUMN IF NOT EXISTS estimated_value_max DECIMAL(10,2) COMMENT 'Maximum estimated value (PHP)',
ADD COLUMN IF NOT EXISTS ai_analysis_generated_at TIMESTAMP NULL DEFAULT NULL COMMENT 'When AI analysis was performed';

CREATE INDEX IF NOT EXISTS idx_products_brand ON products(brand);
CREATE INDEX IF NOT EXISTS idx_products_item_type ON products(item_type);
CREATE INDEX IF NOT EXISTS idx_products_authenticity_risks ON products(authenticity_risks);
Create INDEX IF NOT EXISTS idx_products_estimated_value_min ON products(estimated_value_min);
