-- Migration: Add meetup coordination columns to trades table
-- Date: 2026-04-10

ALTER TABLE trades ADD COLUMN IF NOT EXISTS meetup_location VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS buyer_meetup_confirmed BOOLEAN DEFAULT FALSE;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS seller_meetup_confirmed BOOLEAN DEFAULT FALSE;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS buyer_meetup_location VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS buyer_meetup_time VARCHAR(100) NULL DEFAULT NULL;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS seller_meetup_location VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS seller_meetup_time VARCHAR(100) NULL DEFAULT NULL;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS buyer_met BOOLEAN DEFAULT FALSE;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS seller_met BOOLEAN DEFAULT FALSE;
